import type { Course } from "./types";

export const courseDaily: Course = {
  id: "daily",
  titleJa: "日常会話をこなす",
  subtitleJa: "旅行・雑談・困ったときのやりとり",
  emoji: "✈️",
  level: "intermediate",
  levelLabel: "A2〜B1",
  units: [
    {
      id: "daily-travel",
      titleJa: "旅行と空港",
      descJa: "チェックイン・入国審査・ホテルでのやりとり",
      lessons: [
        {
          id: "daily-travel-phrase",
          kind: "phrase",
          titleJa: "空港とホテルのフレーズ",
          subtitleJa: "移動と宿泊で必ず使う表現",
          level: "intermediate",
          estMinutes: 6,
          xp: 15,
          phrases: [
            { en: "I'd like an aisle seat, if there's one available.", ja: "空いていれば通路側の席がいいのですが。", focus: ["aisle", "available"] },
            { en: "I'm here on holiday for about ten days.", ja: "10日間ほど休暇で来ています。", focus: ["holiday"] },
            { en: "I have a reservation under the name Tanaka.", ja: "田中の名前で予約しています。", focus: ["reservation"] },
            { en: "Could I have a room on a higher floor?", ja: "もう少し上の階の部屋にできますか？", focus: ["higher", "floor"] },
            { en: "What time do I need to check out?", ja: "チェックアウトは何時ですか？", focus: ["check"] },
            { en: "Is breakfast included in the price?", ja: "朝食は料金に含まれていますか？", focus: ["included"] },
            { en: "My flight was delayed, so I arrived late.", ja: "飛行機が遅れたので、到着が遅くなりました。", focus: ["delayed", "arrived"] },
            { en: "Could you keep my luggage until three o'clock?", ja: "3時まで荷物を預かってもらえますか？", focus: ["luggage"] },
          ],
        },
        {
          id: "daily-travel-roleplay",
          kind: "roleplay",
          titleJa: "ホテルにチェックインする",
          subtitleJa: "予約の確認からリクエストまで",
          level: "intermediate",
          estMinutes: 8,
          xp: 20,
          scenario: {
            title: "Checking into a hotel",
            tutorRole: "a polite hotel receptionist in London",
            userRole: "a guest arriving to check in",
            goal: "confirm your reservation, ask about breakfast and check-out time, and make one request about your room",
          },
          openingLine: "Good evening, welcome to the Riverside Hotel. Do you have a reservation with us?",
          openingLineJa: "こんばんは、リバーサイドホテルへようこそ。ご予約はございますか？",
          keyPhrases: [
            { en: "I have a reservation under ...", ja: "…の名前で予約しています。" },
            { en: "Is breakfast included?", ja: "朝食は含まれていますか？" },
            { en: "What time is check-out?", ja: "チェックアウトは何時ですか？" },
            { en: "Would it be possible to ...?", ja: "…することはできますか？" },
          ],
          maxTurns: 9,
        },
        {
          id: "daily-travel-freetalk",
          kind: "freetalk",
          titleJa: "旅行の思い出を話す",
          subtitleJa: "過去形を使って体験を語る",
          level: "intermediate",
          estMinutes: 8,
          xp: 15,
          topic: "a trip you took and what you remember about it",
          promptJa: "これまでに行った旅行について、印象に残っていることを話してみましょう。",
          starters: [
            "The best trip I've taken was to ...",
            "I went somewhere really unexpected last year.",
            "I don't travel much, but I'd like to.",
          ],
          maxTurns: 10,
        },
      ],
    },
    {
      id: "daily-smalltalk",
      titleJa: "友だちとの雑談",
      descJa: "週末の話・感想を言う・話をつなげる",
      lessons: [
        {
          id: "daily-smalltalk-phrase",
          kind: "phrase",
          titleJa: "雑談をつなげるフレーズ",
          subtitleJa: "会話が止まらなくなる言い方",
          level: "intermediate",
          estMinutes: 6,
          xp: 15,
          phrases: [
            { en: "How was your weekend? Did you do anything fun?", ja: "週末はどうだった？何か楽しいことした？", focus: ["weekend"] },
            { en: "Oh really? That sounds great.", ja: "へえ、本当に？それはいいね。", focus: ["really", "sounds"] },
            { en: "The same thing happened to me last month.", ja: "先月、同じことが私にもあったよ。", focus: ["happened"] },
            { en: "I've been meaning to try that place.", ja: "あのお店、ずっと行ってみたいと思ってたんだ。", focus: ["meaning"] },
            { en: "To be honest, I'm not really into that.", ja: "正直言うと、あまり興味がないんだ。", focus: ["honest"] },
            { en: "Speaking of which, have you seen the new one?", ja: "そういえば、新しいの見た？", focus: ["Speaking"] },
            { en: "That reminds me of something similar.", ja: "それで似たようなことを思い出したよ。", focus: ["reminds", "similar"] },
            { en: "Anyway, what have you been up to lately?", ja: "ところで、最近どうしてるの？", focus: ["lately"] },
          ],
        },
        {
          id: "daily-smalltalk-roleplay",
          kind: "roleplay",
          titleJa: "久しぶりの友だちと話す",
          subtitleJa: "近況を伝え合って会話を続ける",
          level: "intermediate",
          estMinutes: 8,
          xp: 20,
          scenario: {
            title: "Running into an old friend",
            tutorRole: "Alex, an old friend you haven't seen in two years",
            userRole: "yourself, bumping into Alex at a station",
            goal: "catch up on what you have both been doing, react to Alex's news, and suggest meeting again",
          },
          openingLine: "Wait — is that you? I haven't seen you in ages! How have you been?",
          openingLineJa: "えっ、もしかして本人？ずいぶん会ってないよね！どうしてた？",
          keyPhrases: [
            { en: "It's been so long! I've been ...", ja: "本当に久しぶり！私は…してたよ。" },
            { en: "That sounds amazing. Tell me more.", ja: "それすごいね。もっと聞かせて。" },
            { en: "What about you? How's work going?", ja: "そっちはどう？仕事は順調？" },
            { en: "We should get together properly sometime.", ja: "今度ちゃんと会おうよ。" },
          ],
          maxTurns: 9,
        },
        {
          id: "daily-smalltalk-freetalk",
          kind: "freetalk",
          titleJa: "趣味と週末の話",
          subtitleJa: "好きなことを詳しく説明する",
          level: "intermediate",
          estMinutes: 8,
          xp: 15,
          topic: "your hobbies and how you spend your free time",
          promptJa: "趣味や休日の過ごし方について、理由も添えて話してみましょう。",
          starters: [
            "I've picked up a new hobby recently.",
            "Most weekends I just relax at home.",
            "There's something I've been doing for years.",
          ],
          maxTurns: 10,
        },
      ],
    },
    {
      id: "daily-trouble",
      titleJa: "体調とトラブル",
      descJa: "具合が悪いと伝える・困りごとを説明する",
      lessons: [
        {
          id: "daily-trouble-phrase",
          kind: "phrase",
          titleJa: "困ったときのフレーズ",
          subtitleJa: "症状やトラブルを説明する",
          level: "intermediate",
          estMinutes: 6,
          xp: 15,
          phrases: [
            { en: "I'm not feeling very well today.", ja: "今日はあまり具合がよくありません。", focus: ["feeling"] },
            { en: "I've had a headache since yesterday morning.", ja: "昨日の朝から頭痛がします。", focus: ["headache"] },
            { en: "Is there a pharmacy near here?", ja: "この近くに薬局はありますか？", focus: ["pharmacy"] },
            { en: "I think I left my bag on the train.", ja: "電車にかばんを置き忘れたと思います。", focus: ["left"] },
            { en: "Could you help me? I'm not sure what to do.", ja: "助けてもらえますか？どうすればいいか分かりません。", focus: ["help"] },
            { en: "My phone isn't working, so I can't call anyone.", ja: "携帯が動かないので、誰にも電話できません。", focus: ["working"] },
            { en: "I'd like to change my appointment, if that's possible.", ja: "可能であれば、予約を変更したいのですが。", focus: ["appointment"] },
            { en: "I'm really sorry, but I'll be about ten minutes late.", ja: "本当にすみませんが、10分ほど遅れます。", focus: ["sorry", "late"] },
          ],
        },
        {
          id: "daily-trouble-roleplay",
          kind: "roleplay",
          titleJa: "薬局で症状を伝える",
          subtitleJa: "症状を説明して相談する",
          level: "intermediate",
          estMinutes: 7,
          xp: 20,
          scenario: {
            title: "At the pharmacy",
            tutorRole: "a pharmacist who asks careful follow-up questions",
            userRole: "a customer who has had a bad cold for three days",
            goal: "describe your symptoms, say how long you've had them, and ask how to take the medicine",
          },
          openingLine: "Hello, how can I help you today?",
          openingLineJa: "こんにちは、今日はどうされましたか？",
          keyPhrases: [
            { en: "I've had a ... since ...", ja: "…から…の症状があります。" },
            { en: "Is there something I can take for it?", ja: "何か飲めるものはありますか？" },
            { en: "How often should I take it?", ja: "どのくらいの頻度で飲めばいいですか？" },
            { en: "Are there any side effects?", ja: "副作用はありますか？" },
          ],
          maxTurns: 8,
        },
        {
          id: "daily-trouble-freetalk",
          kind: "freetalk",
          titleJa: "困った経験を話す",
          subtitleJa: "出来事を順番に説明する",
          level: "intermediate",
          estMinutes: 8,
          xp: 15,
          topic: "a time something went wrong and how you dealt with it",
          promptJa: "うまくいかなかった経験と、どう対処したかを話してみましょう。",
          starters: [
            "Something annoying happened to me recently.",
            "I once lost something really important.",
            "I got completely lost on a trip one time.",
          ],
          maxTurns: 10,
        },
      ],
    },
  ],
};
