import { UNIT_LECTURES } from "./lectures";
import type { Course } from "./types";

export const courseBasics: Course = {
  id: "basics",
  titleJa: "はじめての英会話",
  subtitleJa: "自己紹介から、お店や道でのやりとりまで",
  emoji: "🌱",
  level: "beginner",
  levelLabel: "A1〜A2",
  units: [
    {
      id: "basics-intro",
      titleJa: "自己紹介",
      descJa: "名前・仕事・住んでいる場所を、自分の言葉で言えるようにする",
      lecture: UNIT_LECTURES["basics-intro"]!,
      lessons: [
        {
          id: "basics-intro-phrase",
          kind: "phrase",
          titleJa: "自分のことを話すフレーズ",
          subtitleJa: "8つの基本文を声に出す",
          level: "beginner",
          estMinutes: 5,
          xp: 15,
          phrases: [
            { en: "Hi, I'm Yuki. Nice to meet you.", ja: "こんにちは、ユキです。はじめまして。", focus: ["Nice"] },
            { en: "I'm from Osaka, but I live in Tokyo now.", ja: "大阪出身ですが、今は東京に住んでいます。", focus: ["live"] },
            { en: "I work at a small software company.", ja: "小さなソフトウェア会社で働いています。", focus: ["work"] },
            { en: "I've been studying English for about a year.", ja: "英語を1年くらい勉強しています。", focus: ["studying"] },
            { en: "I usually practice on the train in the morning.", ja: "ふだんは朝の電車で練習しています。", focus: ["practice", "train"] },
            { en: "My hobby is cooking. I make curry every weekend.", ja: "趣味は料理です。毎週末カレーを作ります。", focus: ["really"] },
            { en: "Sorry, could you say that again more slowly?", ja: "すみません、もう少しゆっくり言ってもらえますか？", focus: ["slowly"] },
            { en: "I'm not sure how to say this in English.", ja: "これを英語でどう言うか分かりません。", focus: ["sure"] },
          ],
        },
        {
          id: "basics-intro-roleplay",
          kind: "roleplay",
          titleJa: "初対面の人と話す",
          subtitleJa: "パーティーで隣の人に話しかけられる",
          level: "beginner",
          estMinutes: 7,
          xp: 20,
          scenario: {
            title: "A party in Tokyo",
            tutorRole: "Sam, a friendly American who just moved to Tokyo",
            userRole: "someone at the same party, meeting Sam for the first time",
            goal: "introduce yourself, say where you are from and what you do, and ask Sam two questions about himself",
          },
          openingLine: "Hi there! I don't think we've met. I'm Sam, I just moved here last month.",
          openingLineJa: "こんにちは！初めてですよね。サムです、先月ここに引っ越してきました。",
          keyPhrases: [
            { en: "Nice to meet you. I'm ...", ja: "はじめまして。私は…です。" },
            { en: "How long have you been in Japan?", ja: "日本にはどのくらいいるんですか？" },
            { en: "What brought you to Tokyo?", ja: "どうして東京に来たんですか？" },
            { en: "What do you do for work?", ja: "お仕事は何をされているんですか？" },
          ],
          maxTurns: 8,
        },
        {
          id: "basics-intro-freetalk",
          kind: "freetalk",
          titleJa: "自分のことを自由に話す",
          subtitleJa: "講師の質問に答えながら会話をのばす",
          level: "beginner",
          estMinutes: 8,
          xp: 15,
          topic: "yourself, your work and your daily routine",
          promptJa: "自分のこと、仕事、毎日の習慣について自由に話してみましょう。",
          starters: [
            "Let me tell you about my typical day.",
            "I'd like to talk about my job.",
            "I want to practice talking about my family.",
          ],
          maxTurns: 10,
        },
      ],
    },
    {
      id: "basics-shop",
      titleJa: "買い物とカフェ",
      descJa: "お店で注文する・値段を聞く・支払う",
      lecture: UNIT_LECTURES["basics-shop"]!,
      lessons: [
        {
          id: "basics-shop-phrase",
          kind: "phrase",
          titleJa: "お店で使うフレーズ",
          subtitleJa: "注文と支払いの定番表現",
          level: "beginner",
          estMinutes: 5,
          xp: 15,
          phrases: [
            { en: "Can I have a small latte, please?", ja: "スモールのラテをお願いします。", focus: ["latte"] },
            { en: "I'll have the same, thanks.", ja: "同じものをお願いします。", focus: ["same"] },
            { en: "For here, please. Not to go.", ja: "店内で食べます。持ち帰りではありません。", focus: ["here"] },
            { en: "How much is this one?", ja: "これはいくらですか？", focus: ["much"] },
            { en: "Do you have this in a larger size?", ja: "これの大きいサイズはありますか？", focus: ["larger"] },
            { en: "Can I pay by card?", ja: "カードで払えますか？", focus: ["card"] },
            { en: "Sorry, I think there's a mistake with my order.", ja: "すみません、注文が間違っている気がします。", focus: ["mistake", "order"] },
            { en: "That's all for today. Thank you!", ja: "今日はこれで全部です。ありがとう！", focus: ["all"] },
          ],
        },
        {
          id: "basics-shop-roleplay",
          kind: "roleplay",
          titleJa: "カフェで注文する",
          subtitleJa: "店員とのやりとりを最後までやりきる",
          level: "beginner",
          estMinutes: 6,
          xp: 20,
          scenario: {
            title: "Ordering at a coffee shop",
            tutorRole: "a cheerful barista at a busy coffee shop",
            userRole: "a customer ordering a drink and something to eat",
            goal: "order a drink, order something to eat, and ask for the total",
          },
          openingLine: "Hi! Welcome in. What can I get started for you today?",
          openingLineJa: "こんにちは！いらっしゃいませ。ご注文は何にしますか？",
          keyPhrases: [
            { en: "Can I have a ..., please?", ja: "…をお願いします。" },
            { en: "Could I also get a ...?", ja: "…も一緒にもらえますか？" },
            { en: "How much is that altogether?", ja: "全部でいくらですか？" },
            { en: "For here, please.", ja: "店内でお願いします。" },
          ],
          maxTurns: 8,
        },
        {
          id: "basics-shop-freetalk",
          kind: "freetalk",
          titleJa: "買い物について話す",
          subtitleJa: "好きなお店や最近買ったものを話す",
          level: "beginner",
          estMinutes: 7,
          xp: 15,
          topic: "shopping, your favourite shops and things you bought recently",
          promptJa: "最近買ったものや、よく行くお店について話してみましょう。",
          starters: [
            "I bought something nice last weekend.",
            "There's a shop near my house I really like.",
            "I don't really enjoy shopping, to be honest.",
          ],
          maxTurns: 10,
        },
      ],
    },
    {
      id: "basics-directions",
      titleJa: "道をたずねる",
      descJa: "行き方を聞く・聞き返す・お礼を言う",
      lecture: UNIT_LECTURES["basics-directions"]!,
      lessons: [
        {
          id: "basics-directions-phrase",
          kind: "phrase",
          titleJa: "道をたずねるフレーズ",
          subtitleJa: "聞き返し方までセットで覚える",
          level: "beginner",
          estMinutes: 5,
          xp: 15,
          phrases: [
            { en: "Excuse me, how do I get to the station?", ja: "すみません、駅へはどう行けばいいですか？", focus: ["Excuse"] },
            { en: "Is it far from here?", ja: "ここから遠いですか？", focus: ["far"] },
            { en: "Should I turn left or right?", ja: "左に曲がりますか、右ですか？", focus: ["left", "right"] },
            { en: "How long does it take to walk there?", ja: "歩いてどのくらいかかりますか？", focus: ["walk"] },
            { en: "Sorry, I didn't catch that. Could you repeat it?", ja: "すみません、聞き取れませんでした。もう一度お願いできますか？", focus: ["repeat"] },
            { en: "Could you show me on the map?", ja: "地図で示してもらえますか？", focus: ["show"] },
            { en: "So I go straight and then turn right. Is that correct?", ja: "まっすぐ行って、それから右ですね。合っていますか？", focus: ["straight", "correct"] },
            { en: "Thanks a lot. You've been very helpful.", ja: "本当にありがとうございます。とても助かりました。", focus: ["helpful"] },
          ],
        },
        {
          id: "basics-directions-roleplay",
          kind: "roleplay",
          titleJa: "駅までの道を聞く",
          subtitleJa: "分からないところを聞き返して確認する",
          level: "beginner",
          estMinutes: 6,
          xp: 20,
          scenario: {
            title: "Lost near the station",
            tutorRole: "a helpful local person on the street",
            userRole: "a traveller who is lost and looking for the train station",
            goal: "ask the way to the station, ask how long it takes, and repeat the directions back to check you understood",
          },
          openingLine: "You look a little lost. Are you looking for something?",
          openingLineJa: "少し迷っているみたいですね。何かお探しですか？",
          keyPhrases: [
            { en: "How do I get to ...?", ja: "…へはどう行けばいいですか？" },
            { en: "How long does it take?", ja: "どのくらいかかりますか？" },
            { en: "So, I go ... and then ...?", ja: "つまり…して、それから…ですね？" },
            { en: "Could you say that again, please?", ja: "もう一度言っていただけますか？" },
          ],
          maxTurns: 8,
        },
        {
          id: "basics-directions-freetalk",
          kind: "freetalk",
          titleJa: "自分の町について話す",
          subtitleJa: "住んでいる場所を紹介する",
          level: "beginner",
          estMinutes: 7,
          xp: 15,
          topic: "the area where you live and how you get around",
          promptJa: "住んでいる町や、ふだんの移動手段について話してみましょう。",
          starters: [
            "I live about twenty minutes from the station.",
            "My neighbourhood is pretty quiet.",
            "I usually take the train everywhere.",
          ],
          maxTurns: 10,
        },
      ],
    },
  ],
};
