import { UNIT_LECTURES } from "./lectures";
import type { Course } from "./types";

export const courseBusiness: Course = {
  id: "business",
  titleJa: "ビジネス英語の基礎",
  subtitleJa: "会議で意見を言い、面接で自分を伝える",
  emoji: "💼",
  level: "advanced",
  levelLabel: "B1〜B2",
  units: [
    {
      id: "business-meeting",
      titleJa: "会議で意見を言う",
      descJa: "賛成・反対・提案を、理由をつけて伝える",
      lecture: UNIT_LECTURES["business-meeting"]!,
      lessons: [
        {
          id: "business-meeting-phrase",
          kind: "phrase",
          titleJa: "会議で使うフレーズ",
          subtitleJa: "意見・反論・確認の言い方",
          level: "advanced",
          estMinutes: 7,
          xp: 15,
          phrases: [
            { en: "I'd like to add something to that, if I may.", ja: "よろしければ、それに少し付け加えたいのですが。", focus: ["add"] },
            { en: "That's a fair point, but I see it slightly differently.", ja: "おっしゃることは分かりますが、私は少し違う見方をしています。", focus: ["fair", "differently"] },
            { en: "From what I've seen, the main issue is the timeline.", ja: "私の見たところ、主な問題はスケジュールです。", focus: ["issue", "timeline"] },
            { en: "Could we come back to that point later?", ja: "その点は後で戻ってきてもいいですか？", focus: ["later"] },
            { en: "Just to make sure I understand, are you suggesting we delay it?", ja: "確認させてください、延期するという提案でしょうか？", focus: ["suggesting"] },
            { en: "I'd rather we tested it before committing to a date.", ja: "日程を決める前に検証したほうがいいと思います。", focus: ["rather", "committing"] },
            { en: "Let me follow up on that and get back to you by Friday.", ja: "その件は確認して、金曜日までにご連絡します。", focus: ["follow"] },
            { en: "So, to summarise, we've agreed on the first two items.", ja: "まとめると、最初の2点については合意しました。", focus: ["summarise", "agreed"] },
          ],
        },
        {
          id: "business-meeting-roleplay",
          kind: "roleplay",
          titleJa: "スケジュールについて議論する",
          subtitleJa: "反対意見を丁寧に伝える",
          level: "advanced",
          estMinutes: 9,
          xp: 20,
          scenario: {
            title: "A project planning meeting",
            tutorRole: "Dana, a project manager who wants to ship two weeks earlier",
            userRole: "an engineer on the project who thinks the deadline is too tight",
            goal: "disagree politely, give two concrete reasons, and propose an alternative plan",
          },
          openingLine: "Thanks for joining. I've been looking at the schedule, and I think we could bring the launch forward by two weeks. What do you think?",
          openingLineJa: "集まってくれてありがとう。スケジュールを見ていて、リリースを2週間早められると思うんだけど、どう思う？",
          keyPhrases: [
            { en: "I understand the pressure, but ...", ja: "急ぎたい理由は分かりますが、…" },
            { en: "My main concern is that ...", ja: "一番気になっているのは…です。" },
            { en: "What if we ... instead?", ja: "代わりに…してはどうでしょう？" },
            { en: "Could we revisit this once we have the data?", ja: "データが出てから再検討できますか？" },
          ],
          maxTurns: 10,
        },
        {
          id: "business-meeting-freetalk",
          kind: "freetalk",
          titleJa: "仕事について話す",
          subtitleJa: "業務内容と課題を説明する",
          level: "advanced",
          estMinutes: 9,
          xp: 15,
          topic: "your work, what you are responsible for, and a current challenge",
          promptJa: "今の仕事の内容と、いま直面している課題について話してみましょう。",
          starters: [
            "My role mainly involves ...",
            "The hardest part of my job right now is ...",
            "We're in the middle of a big project at the moment.",
          ],
          maxTurns: 10,
        },
      ],
    },
    {
      id: "business-interview",
      titleJa: "英語面接",
      descJa: "強みを伝える・経験を語る・逆質問する",
      lecture: UNIT_LECTURES["business-interview"]!,
      lessons: [
        {
          id: "business-interview-phrase",
          kind: "phrase",
          titleJa: "面接で使うフレーズ",
          subtitleJa: "経験と強みを具体的に語る",
          level: "advanced",
          estMinutes: 7,
          xp: 15,
          phrases: [
            { en: "I've spent the last five years working in software development.", ja: "この5年間はソフトウェア開発の仕事をしてきました。", focus: ["development"] },
            { en: "My strongest skill is probably breaking down complex problems.", ja: "一番の強みは、複雑な問題を分解することだと思います。", focus: ["strongest", "complex"] },
            { en: "In my previous role, I led a team of four engineers.", ja: "前職では、4人のエンジニアのチームを率いていました。", focus: ["previous", "led"] },
            { en: "One project I'm particularly proud of is our payment system.", ja: "特に誇りに思っているのは、決済システムのプロジェクトです。", focus: ["particularly", "proud"] },
            { en: "I'm looking for a role where I can take on more responsibility.", ja: "より大きな責任を持てる役割を探しています。", focus: ["responsibility"] },
            { en: "That's a good question. Let me think for a moment.", ja: "いい質問ですね。少し考えさせてください。", focus: ["question"] },
            { en: "Could you tell me more about how the team works together?", ja: "チームがどのように協力しているか、もう少し教えていただけますか？", focus: ["together"] },
            { en: "What would success look like in the first six months?", ja: "最初の半年で成果とされるのはどんなことでしょうか？", focus: ["success"] },
          ],
        },
        {
          id: "business-interview-roleplay",
          kind: "roleplay",
          titleJa: "英語の面接を受ける",
          subtitleJa: "強みと経験を具体例で伝える",
          level: "advanced",
          estMinutes: 10,
          xp: 20,
          scenario: {
            title: "A job interview",
            tutorRole: "Morgan, a hiring manager conducting a friendly but probing interview",
            userRole: "a candidate interviewing for a role you want",
            goal: "describe your experience with a concrete example, explain why you want the role, and ask the interviewer two questions",
          },
          openingLine: "Thanks for coming in today. To start, could you tell me a little about your background?",
          openingLineJa: "本日はお越しいただきありがとうございます。まず、これまでのご経歴を少し伺えますか？",
          keyPhrases: [
            { en: "I've been working in ... for ... years.", ja: "…の分野で…年働いています。" },
            { en: "For example, at my last company I ...", ja: "たとえば前の会社では…しました。" },
            { en: "What appeals to me about this role is ...", ja: "この仕事に惹かれているのは…です。" },
            { en: "May I ask you a couple of questions?", ja: "いくつか質問してもよろしいですか？" },
          ],
          maxTurns: 10,
        },
        {
          id: "business-interview-freetalk",
          kind: "freetalk",
          titleJa: "キャリアについて話す",
          subtitleJa: "これまでとこれからを語る",
          level: "advanced",
          estMinutes: 9,
          xp: 15,
          topic: "your career so far and where you want it to go",
          promptJa: "これまでのキャリアと、これからやりたいことについて話してみましょう。",
          starters: [
            "I didn't plan my career, it just happened this way.",
            "In five years, I'd like to be ...",
            "The biggest turning point for me was ...",
          ],
          maxTurns: 10,
        },
      ],
    },
  ],
};
